version: "3.8"
services:
  db:
    platform: linux/x86_64
    image: mysql:8.0.33
    container_name: flask-backend-db
    environment:
      MYSQL_ROOT_PASSWORD: flask-db
      MYSQL_PASSWORD: flask-db
    ports:
      - "3666:3306"
    volumes:
      - ./db/mysql/volumes:/var/lib/mysql
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: flask-backend
    # デバッグ時に面倒なのであとで設定
    # command: bash -c "gunicorn app:app -c /api/config/gunicorn_settings.py"
    # あとでapp配下の設定から読むように｀
    command: bash -c "flask --debug run --host=0.0.0.0 --port=80"
    volumes:
      - .:/api
    ports:
      - "8000:80"
    environment:
      - RELOAD=${RELOAD}
      - DEBUG=${DEBUG}
      - LOG=${LOG}
      - LOG_LEVEL=${LOG_LEVEL}
    depends_on:
      - db
